### ISSUE TITLE
Fine-tune Error: Cannot load weights from pre-trained checkpoint file.

### ISSUE THREAD

**Issue by youlandasu** [facebookresearch/Zero-Shot-DST#3]
I got the following error when loading model weights from the pre-trained zero-shot model:

`RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/94629029024880: invalid header or archive is corrupted`

Here is the environment I use:
> python=3.7.11
>torch=1.7.0
>transformers=3.1.0
>pytorch-lightning=1.1.1

**Comment by h-guo18** [comment]
Hi ! I encounter the same issue with the same environments as you. Is there any solution?

**Comment by youlandasu** [comment]
> Hi ! I encounter the same issue with the same environments as you. Is there any solution?

I suppose it is because saving and loading models are in different torch versions, even though I followed the given environment requirements on my end. By the way, I save the entire model with `torch.save()` instead.

**Comment by zlinao** [comment]
Yes, this error is expected when you trying to load a model with different pytorch version.
